export const API_CALL_REQUESTED= 'PI_CALL_REQUESTED';
export const API_CALL_FULFILLED= 'API_CALL_FULFILLED';
export const API_CALL_REJECTED= 'API_CALL_REJECTED';
export const GET_ALL_PEOPLE= 'GET_ALL_PEOPLE';
export const GET_VEHICLE_BY_PEOPLE= 'GET_VEHICLE_BY_PEOPLE';